### ISSUE TITLE
카피그룹 리팩토링(수정사항 반영)

### ISSUE THREAD

**Issue by kang0906** [swcamp-teamP03/Backend#20]
## 💡 issue

[refator]카피그룹 리팩토링(수정사항 반영)

## 📝 todo
- [x] 카피그룹 리스트 API response 수정 
  - 변수명 수정 copyList -> GroupList
- [x] 카피그룹 생성 API requset 수정 
  - 변수 타입 createCount ( String - > int) /  copyLength ( String - > int)
- [x] Entity 수정
  - ERD 반영
    - CopyGroup
    - GptCopy 
- [x] 캠페인 생성시 카피그룹 수정불가 하도록 CopyGroupService 로직 수정
- [x] response 할때 common.ResponseDto 사용
