### ISSUE TITLE
캠페인 생성 테스트 코드 작성

### ISSUE THREAD

**Issue by kang0906** [swcamp-teamP03/Backend#51]
캠페인 생성 테스트 코드 작성
---

## 💡 issue
[test] 캠페인 생성 테스트 코드 작성

## 📝 todo
- [x] 문자 api  사용 여부에 따라 동작하도록 api 수정 (테스트 때는 데이터만 생성 , 실제 문자 발송 X)
- [x] ab테스트 사용
  - [x] 정상 시나리오 테스트
    - [x] 캠페인 생성 성공
  - [x] 비정상 시나리오 테스트
    - [x] 존재하지 않는 카피그룹, 고객그룹 사용했을경우 ( 404 ) 
 - [x] ab테스트 사용 X
    - [x] 정상 시나리오 테스트
      - [x] 캠페인 생성 성공
    - [x] 비정상 시나리오 테스트
      - [x] 존재하지 않는 카피그룹, 고객그룹 사용했을경우 ( 404 )
