### ISSUE TITLE
카피 생성 api  수정

### ISSUE THREAD

**Issue by kang0906** [swcamp-teamP03/Backend#83]
# tasks
 - [x] copyGroup Entity 수정
 - [x] 카피 그룹 생성 api 수정
 - [x] 카피(광고문자) 생성 api 수정 (ChatGpt 연동 api)
 - [x] 카피 그룹 상세조회 api 수정
 ---
# 카피그룹 api 명세 수정 (작성일 : 4.9)
### 요청, 응답 바디 
- 수정사항 
    - "type" : **기존 "카피 유형" (ex: 광고, 홍보) -> "문장길이" (길게, 짧게)** 로 변경
        - if else 문으로 처리할 예정 if(짧게) {짧게 생성} else {길게 생성} 
    - "sector" : **기존 "업종" -> "상품,서비스 카테고리"** 로 변경
    - "copyLength" 요소 삭제
- 추가된 요소
    - "targetAge" : "타겟 연령" ("20대", "30대" ...)
    - "targetGender" : "타겟 성별" ("남성" or "여성")
---
- 수정된 api
    - 카피 그룹 상세
    - 카피 그룹 생성
    - 카피 (광고문자) 생성
